server:
  port: 10011
  servlet:
    context-path: /renshe
spring:
  profiles:
    active: prop
#    配置文件传输
  servlet:
    multipart:
      enabled: true
#      单个数据的大小
      max-file-size: 20MB
#      总数据的大小
      max-request-size: 100MB
mybatis-plus:
#  配置文件位置
  mapper-locations: classpath:mapper/*.xml
#  别名包扫描路径
  typeAliasesPackage: com.ciyun.renshe.entity


