package com.ciyun.renshe.wsdl.cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2020-07-06T09:47:30.432+08:00
 * Generated source version: 3.3.4
 *
 */
@WebService(targetNamespace = "http://www.eastrobot.cn/ws/RobotServiceEx", name = "RobotServiceEx")
@XmlSeeAlso({ObjectFactory.class})
public interface RobotServiceEx {

    @WebMethod(action = "http://www.eastrobot.cn/ws/RobotServiceEx/closeSession")
    @RequestWrapper(localName = "closeSession", targetNamespace = "http://www.eastrobot.cn/ws/RobotServiceEx", className = "com.ciyun.renshe.wsdl.cxf.CloseSession")
    @ResponseWrapper(localName = "closeSessionResponse", targetNamespace = "http://www.eastrobot.cn/ws/RobotServiceEx", className = "com.ciyun.renshe.wsdl.cxf.CloseSessionResponse")
    @WebResult(name = "robotResponse", targetNamespace = "")
    public com.ciyun.renshe.wsdl.cxf.RobotResponse closeSession(

        @WebParam(name = "robotRequest", targetNamespace = "")
        com.ciyun.renshe.wsdl.cxf.RobotRequest robotRequest
    );

    @WebMethod(action = "http://www.eastrobot.cn/ws/RobotServiceEx/deliver")
    @RequestWrapper(localName = "deliver", targetNamespace = "http://www.eastrobot.cn/ws/RobotServiceEx", className = "com.ciyun.renshe.wsdl.cxf.Deliver")
    @ResponseWrapper(localName = "deliverResponse", targetNamespace = "http://www.eastrobot.cn/ws/RobotServiceEx", className = "com.ciyun.renshe.wsdl.cxf.DeliverResponse")
    @WebResult(name = "robotResponse", targetNamespace = "")
    public com.ciyun.renshe.wsdl.cxf.RobotResponse deliver(

        @WebParam(name = "robotRequest", targetNamespace = "")
        com.ciyun.renshe.wsdl.cxf.RobotRequest robotRequest
    );

    @WebMethod(action = "http://www.eastrobot.cn/ws/RobotServiceEx/openSession")
    @RequestWrapper(localName = "openSession", targetNamespace = "http://www.eastrobot.cn/ws/RobotServiceEx", className = "com.ciyun.renshe.wsdl.cxf.OpenSession")
    @ResponseWrapper(localName = "openSessionResponse", targetNamespace = "http://www.eastrobot.cn/ws/RobotServiceEx", className = "com.ciyun.renshe.wsdl.cxf.OpenSessionResponse")
    @WebResult(name = "robotResponse", targetNamespace = "")
    public com.ciyun.renshe.wsdl.cxf.RobotResponse openSession(

        @WebParam(name = "robotRequest", targetNamespace = "")
        com.ciyun.renshe.wsdl.cxf.RobotRequest robotRequest
    );
}
