
package com.ciyun.renshe.wsdl.cxf;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2020-07-06T09:47:30.286+08:00
 * Generated source version: 3.3.4
 *
 */
public final class RobotServiceEx_DefaultRobotServiceExPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.eastrobot.cn/ws/RobotServiceEx", "RobotServiceEx");

    private RobotServiceEx_DefaultRobotServiceExPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RobotServiceEx_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        RobotServiceEx_Service ss = new RobotServiceEx_Service(wsdlURL, SERVICE_NAME);
        RobotServiceEx port = ss.getDefaultRobotServiceExPort();

        {
        System.out.println("Invoking closeSession...");
        com.ciyun.renshe.wsdl.cxf.RobotRequest _closeSession_robotRequest = null;
        com.ciyun.renshe.wsdl.cxf.RobotResponse _closeSession__return = port.closeSession(_closeSession_robotRequest);
        System.out.println("closeSession.result=" + _closeSession__return);


        }
        {
        System.out.println("Invoking deliver...");
        com.ciyun.renshe.wsdl.cxf.RobotRequest _deliver_robotRequest = null;
        com.ciyun.renshe.wsdl.cxf.RobotResponse _deliver__return = port.deliver(_deliver_robotRequest);
        System.out.println("deliver.result=" + _deliver__return);


        }
        {
        System.out.println("Invoking openSession...");
        com.ciyun.renshe.wsdl.cxf.RobotRequest _openSession_robotRequest = null;
        com.ciyun.renshe.wsdl.cxf.RobotResponse _openSession__return = port.openSession(_openSession_robotRequest);
        System.out.println("openSession.result=" + _openSession__return);


        }

        System.exit(0);
    }

}
